"""Manage lists of words to use for generating challenges."""

import random

WORDS = {
    'would',
    'think',
    'could',
    'should',
    'leave',
    'start',
    'become',
    'happen',
    'might',
    'believe',
    'write',
    'bring',
    'begin',
    'provide',
    'thank',
    'change',
    'watch',
    'create',
    'learn',
    'include',
    'stand',
    'follow',
    'remember',
    'speak',
    'allow',
    'continue',
    'spend',
    'consider',
    'offer',
    'build',
    'expect',
    'appear',
    'serve',
    'break',
    'require',
    'listen',
    'agree',
    'decide',
    'report',
    'suggest',
    'support',
    'receive',
    'drive',
    'reach',
    'remain',
    'explain',
    'raise',
    'return',
    'choose',
    'cause',
    'people',
    'thing',
    'woman',
    'world',
    'child',
    'school',
    'state',
    'family',
    'president',
    'house',
    'student',
    'place',
    'problem',
    'country',
    'point',
    'group',
    'question',
    'night',
    'number',
    'money',
    'system',
    'company',
    'story',
    'friend',
    'right',
    'month',
    'program',
    'business',
    'study',
    'issue',
    'percent',
    'power',
    'mother',
    'water',
    'service',
    'person',
    'father',
    'minute',
    'party',
    'health',
    'reason',
    'member',
    'community',
    'level',
    'change',
    'center',
    'history',
    'result',
    'morning',
    'parent',
}


def sample(num):
    """Return num random words from the fixed list."""

    return random.sample(WORDS, num)
